# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(behavior_queue)
target_sources(app PRIVATE src/main.c)
target_include_directories(app PRIVATE ../../include)
target_compile_definitions(app PRIVATE CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=4 CONFIG_ZMK_LOG_LEVEL=0)
if(TEST_SPLIT)
  target_compile_definitions(app PRIVATE CONFIG_ZMK_SPLIT=1)
endif()
